-- CreateTable
CREATE TABLE `Minecraft_IGNs` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LatestName` VARCHAR(45) NOT NULL,
    `PlayerUUID` LONGTEXT NOT NULL,
    `DiscordID` LONGTEXT NOT NULL,
    `CreatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

