-- CreateTable
CREATE TABLE `Minecraft_IGNs` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `LatestName` VARCHAR(45) NOT NULL,
    `PlayerUUID` LONGTEXT NOT NULL,
    `DiscordID` LONGTEXT NOT NULL,
    `CreatedAT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `id_UNIQUE`(`id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

